### ISSUE TITLE
Lag spikes 1.10.2

### ISSUE THREAD

**Issue by victorbrndls** [p455w0rd/p455w0rd-s-Things#40]
[08:40:56] [Client thread/INFO]: [CHAT] The server appears to have lag spiked.
[08:40:56] [Client thread/INFO]: [CHAT] Last tick 0.21190846s ago."Server thread" RUNNABLE
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.world.World.func_175625_s(World.java:2402)
[08:40:56] [Client thread/INFO]: [CHAT] 	at p455w0rd.p455w0rdsthings.integration.EnderIo.getNearbyAversionObelisks(EnderIo.java:56)
[08:40:56] [Client thread/INFO]: [CHAT] 	at p455w0rd.p455w0rdsthings.integration.EnderIo.getAversionObelisksInRangeOfEntityApplicable(EnderIo.java:66)
[08:40:56] [Client thread/INFO]: [CHAT] 	at p455w0rd.p455w0rdsthings.integration.EnderIo.isEntityAverted(EnderIo.java:79)
[08:40:56] [Client thread/INFO]: [CHAT] 	at p455w0rd.p455w0rdsthings.entity.EntityEnderman2.func_70601_bi(EntityEnderman2.java:337)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:151)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
[08:40:56] [Client thread/INFO]: [CHAT] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[08:40:56] [Client thread/INFO]: [CHAT] 	at java.lang.Thread.run(Thread.java:745)
[08:40:56] [Client thread/INFO]: [CHAT] 
[08:40:56] [Client thread/INFO]: [CHAT] 

Every time this happen my game freezes for some seconds
Using Forge 12.18.3.2422
P455sw0rdLib - 1.10.2-1.0.30
P455sw0rdThings - 1.10.2-2.2.31

**Comment by p455w0rd** [comment]
working on this now...probably will throw this search functionality into its own thread separate from the main thread..I'll have to see how this works out..thanks for the report!

**Comment by p455w0rd** [comment]
what mod are you using that gives you this info?

**Comment by victorbrndls** [comment]
TickProfiler
