### ISSUE TITLE
Invalid update packets

### ISSUE THREAD

**Issue by Sir-Will** [p455w0rd/p455w0rd-s-Things#58]
In the client log this error gets spamed:
```
[18:02:54] [Client thread/ERROR]: Received invalid update packet for null tile entity at BlockPos{x=-1775, y=252, z=-1783} with data: {PWMachine:{HasRSSignal:0b,RedstoneMode:0,UpgradeInventory:[],Energy:16000000,OwnerID:"66be1da5-e93e-41fe-a087-1f8a2a848f05",Capacity:16000000,AccessMode:0,AccessList:[]},ForgeData:{SpongeData:{}},x:-1775,Compressor:{EnergyUsed:0,IsCooking:0b,EnergyPerTick:50,Inventory:[]},y:252,z:-1783,id:"p455w0rdsthings:compressor"}
[18:02:54] [Client thread/ERROR]: Received invalid update packet for null tile entity at BlockPos{x=-1775, y=252, z=-1783} with data: {PWMachine:{HasRSSignal:0b,RedstoneMode:0,UpgradeInventory:[],Energy:16000000,OwnerID:"66be1da5-e93e-41fe-a087-1f8a2a848f05",Capacity:16000000,AccessMode:0,AccessList:[]},ForgeData:{SpongeData:{}},x:-1775,Compressor:{EnergyUsed:0,IsCooking:0b,EnergyPerTick:50,Inventory:[]},y:252,z:-1783,id:"p455w0rdsthings:compressor"}
```
Teleported to that location and there is only air.

In the server console it spams this:
```
[18:08:20] [Netty Epoll Server IO #9/WARN] [io.netty.channel.DefaultChannelPipeline]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while writev(...): Connection reset by peer
	at io.netty.channel.epoll.Native.$$YJP$$writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.Native.writevAddresses(Native.java) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
but I'm not 100% sure if this is related as it sometimes only spams in the client log and not server console.
That console spam also happens on a other server where the "things" mod is not installed but the lib mod with mods like WirelessCraftingTerminal, so this might be an general issue with your packet handling in the library mod.

p455w0rdsthings-1.10.2-2.2.32

**Comment by p455w0rd** [comment]
to put it simple..i'm not supporting 1.10.2 anymore..i appreciate your taking time to try and help, but I just don't have time..sorry
